USE [master]
GO

/****** Object:  Database [centro_salud]    Script Date: 02/04/2015 23:16:18 ******/
CREATE DATABASE [centro_salud] ON  PRIMARY 
( NAME = N'centro_salud', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\centro_salud.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'centro_salud_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\centro_salud_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [centro_salud] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [centro_salud].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [centro_salud] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [centro_salud] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [centro_salud] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [centro_salud] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [centro_salud] SET ARITHABORT OFF 
GO

ALTER DATABASE [centro_salud] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [centro_salud] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [centro_salud] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [centro_salud] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [centro_salud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [centro_salud] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [centro_salud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [centro_salud] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [centro_salud] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [centro_salud] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [centro_salud] SET  DISABLE_BROKER 
GO

ALTER DATABASE [centro_salud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [centro_salud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [centro_salud] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [centro_salud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [centro_salud] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [centro_salud] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [centro_salud] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [centro_salud] SET  READ_WRITE 
GO

ALTER DATABASE [centro_salud] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [centro_salud] SET  MULTI_USER 
GO

ALTER DATABASE [centro_salud] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [centro_salud] SET DB_CHAINING OFF 
GO

