///////////////////////////////////////////////////////////
//  Comprobante.cs
//  Implementation of the Class Comprobante
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:20
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

public class Comprobante {

	private bool estado;
	private DateTime fechaComprobante;
	private int nroComprobante;
	public TipoComprobante m_TipoComprobante;
	public DetalleComprobante m_DetalleComprobante;
	public IUsuario m_Usuario;

	public Comprobante(){

	}

	~Comprobante(){

	}

	public virtual void Dispose(){

	}

}//end Comprobante