///////////////////////////////////////////////////////////
//  DetalleDonacion.cs
//  Implementation of the Class DetalleDonacion
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:20
///////////////////////////////////////////////////////////




public class DetalleDonacion : DetalleComprobante {

	private string comentario;

	public DetalleDonacion(){

	}

	~DetalleDonacion(){

	}

	public override void Dispose(){

	}

}//end DetalleDonacion