///////////////////////////////////////////////////////////
//  DetalleMovimiento.cs
//  Implementation of the Class DetalleMovimiento
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:20
///////////////////////////////////////////////////////////




public class DetalleMovimiento {

	private int cantidad;
	public Medicamento m_Medicamento;

	public DetalleMovimiento(){

	}

	~DetalleMovimiento(){

	}

	public virtual void Dispose(){

	}

}//end DetalleMovimiento