///////////////////////////////////////////////////////////
//  DetalleComprobante.cs
//  Implementation of the Class DetalleComprobante
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:20
///////////////////////////////////////////////////////////




public class DetalleComprobante {

	private int cantidadEntregada;
	private int cantidadSolicitada;
	public TipoMedicamento m_TipoMedicamento;

	public DetalleComprobante(){

	}

	~DetalleComprobante(){

	}

	public virtual void Dispose(){

	}

}//end DetalleComprobante