///////////////////////////////////////////////////////////
//  DetalleReceta.cs
//  Implementation of the Class DetalleReceta
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:20
///////////////////////////////////////////////////////////




public class DetalleReceta : DetalleComprobante {

	public DetalleReceta(){

	}

	~DetalleReceta(){

	}

	public override void Dispose(){

	}

}//end DetalleReceta