///////////////////////////////////////////////////////////
//  Donacion.cs
//  Implementation of the Class Donacion
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:21
///////////////////////////////////////////////////////////




public class Donacion : Comprobante {

	private int efectorDestino;
	private int efectorOrigen;

	public Donacion(){

	}

	~Donacion(){

	}

	public override void Dispose(){

	}

}//end Donacion