///////////////////////////////////////////////////////////
//  DetalleMovimientoStock.cs
//  Implementation of the Class DetalleMovimientoStock
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:21
///////////////////////////////////////////////////////////


using System;
using Centro_Salud.Persistencia;
using Centro_Salud;
using System.Collections.Generic;
using Centro_Salud.Presentacion;
using System.Linq;

namespace Centro_Salud.Persistencia{
public class IDetalleMovimientoStock:Intermediario {

	private int nroMovimiento;
    private int codigoMedicamento;
    private int nroLote;
    private int cantidad;

	

	public IDetalleMovimientoStock(){

	}

	~IDetalleMovimientoStock(){

	}
     public override void save<T>(T entity){
      try
        {
            DetalleMovimientoStock detmovstk = entity as DetalleMovimientoStock;
            
            dao.DetalleMovimientoStocks.InsertOnSubmit(detmovstk);
                    
        }
        catch (Exception ex)
        {
            throw new Exception("Error al guardar" + ex.Message);
        }
    
    }

	public virtual void Dispose(){

	}

    public override void Delete(int id)
    {
        throw new NotImplementedException();
    }
    public override void Update<T>(T entity)
    {
        throw new NotImplementedException();
    }
    public override List<T> getByCriterio<T>(string att, string op, string val)
    {
        throw new NotImplementedException();
    }
    public override IList<T> getPorCriterio<T>(string name)
    {

        return (from detmovstk in dao.DetalleMovimientoStocks where detmovstk.nroMovimiento == int.Parse(name) select detmovstk).ToList() as List<T>; //.SingleOrDefault() as List<T>; //retorna un solo Producto
    }

    public override object getPorId(int id)
    {
        throw new NotImplementedException();
    }
    public override IList<T> getCriterioById<T>(string att, string op, int val)
    {
        return (from det in dao.DetalleMovimientoStocks where det.nroMovimiento == val select det).ToList() as List<T>;
    }
    public override List<T> getAll<T>()
    {
        return (from detmovstk in dao.DetalleMovimientoStocks select detmovstk).ToList() as List<T>;
    }
	

}//end DetalleMovimientoStock
}