///////////////////////////////////////////////////////////
//  Lote.cs
//  Implementation of the Class Lote
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:21
///////////////////////////////////////////////////////////

using System;
using Centro_Salud.Persistencia;
using Centro_Salud;
using System.Collections.Generic;
using Centro_Salud.Presentacion;
using System.Linq;

namespace Centro_Salud.Persistencia
{
    public class ILote : Intermediario
    {

        private DateTime fechaElaboracion;
        private DateTime fechaVto;
        private int nroLote;

        public ILote()
        {

        }

        ~ILote()
        {

        }

        public virtual void Dispose()
        {

        }

        public override void save<T>(T entity)
        {
            try
            {
                Lote lote = entity as Lote;

                dao.Lotes.InsertOnSubmit(lote);

            }
            catch (Exception ex)
            {
                throw new Exception("Error al guardar" + ex.Message);
            }

        }

        public override void Delete(int id)
        {
            throw new NotImplementedException();
        }
        public override void Update<T>(T entity)
        {
            throw new NotImplementedException();
        }
        public override List<T> getByCriterio<T>(string att, string op, string val)
        {
            return (from l in dao.Lotes where l.nroLote == Convert.ToInt32(val) select l).ToList() as List<T>;
            //throw new NotImplementedException();
        }
        public override IList<T> getPorCriterio<T>(string name)
        {
            throw new NotImplementedException();
            // return (from lote in dao.Lotes where lote.descripcion == name select med).ToList() as List<T>; //.SingleOrDefault() as List<T>; //retorna un solo Producto
        }

        public override object getPorId(int id)
        {
            throw new NotImplementedException();
        }
        public override IList<T> getCriterioById<T>(string att, string op, int val)
        {
            return (from l in dao.Lotes where l.nroLote == val select l).ToList() as List<T>;
        }
        public override List<T> getAll<T>()
        {
            return (from lote in dao.Lotes select lote).ToList() as List<T>;
        }




    }//end Lote
}