///////////////////////////////////////////////////////////
//  Medicamento.cs
//  Implementation of the Class Medicamento
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:21
///////////////////////////////////////////////////////////


using System;
using Centro_Salud.Persistencia;
using Centro_Salud;
using System.Collections.Generic;
using Centro_Salud.Presentacion;
using System.Linq;


public class Medicamento {

	public Lote m_Lote;
	public TipoMedicamento m_TipoMedicamento;

	public Medicamento(){

	}

	~Medicamento(){

	}

	public virtual void Dispose(){

	}

}//end Medicamento