///////////////////////////////////////////////////////////
//  Paciente.cs
//  Implementation of the Class Paciente
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:22
///////////////////////////////////////////////////////////


using System;

public class Paciente {

	private int DNI;
	private string domicilio;
	private DateTime fechaNacimiento;
	private string nombrePaciente;
	private int nroPaciente;
	private int telefono;
	private int tipoDocumento;

	public Paciente(){

	}

	~Paciente(){

	}

	public virtual void Dispose(){

	}

}//end Paciente