///////////////////////////////////////////////////////////
//  PerfilPrivilegio.cs
//  Implementation of the Class PerfilPrivilegio
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:22
///////////////////////////////////////////////////////////

using System;


public class PerfilPrivilegio {

	private DateTime fechaDesde;
	private DateTime fechaHasta;
	public Perfil m_Perfil;
	//public Privilegio m_Privilegio;

	public PerfilPrivilegio(){

	}

	~PerfilPrivilegio(){

	}

	public virtual void Dispose(){

	}

}//end PerfilPrivilegio