///////////////////////////////////////////////////////////
//  Perfil.cs
//  Implementation of the Class Perfil
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:22
///////////////////////////////////////////////////////////


using System;

public class Perfil {

	private int codigoPerfil;
	private string descripcion;

	public Perfil(){

	}

	~Perfil(){

	}

	public virtual void Dispose(){

	}

}//end Perfil