///////////////////////////////////////////////////////////
//  Privilegio.cs
//  Implementation of the Class Privilegio
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:22
///////////////////////////////////////////////////////////




public class Privilegio {

	private int codigo;
	private string descripcion;

	public Privilegio(){

	}

	~Privilegio(){

	}

	public virtual void Dispose(){

	}

}//end Privilegio