///////////////////////////////////////////////////////////
//  Receta.cs
//  Implementation of the Class Receta
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:23
///////////////////////////////////////////////////////////


using System;

public class Receta : Comprobante {

	private DateTime fechaEntrega;
	private DateTime fechaVigencia;
	public Medico m_Medico;
	//public Enfermedad m_Enfermedad;
	public Paciente m_Paciente;

	public Receta(){

	}

	~Receta(){

	}

	public override void Dispose(){

	}

}//end Receta