///////////////////////////////////////////////////////////
//  StockMedicamento.cs
//  Implementation of the Class StockMedicamento
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:23
///////////////////////////////////////////////////////////


using System;
using System.Collections;

public class StockMedicamento {

	private DateTime fecha;
	private int stockActual;
	private int stockIncioMes;
	private int stockMinimo;

	public StockMedicamento(){

	}

	~StockMedicamento(){

	}

	public virtual void Dispose(){

	}

}//end StockMedicamento