///////////////////////////////////////////////////////////
//  TipoComprobante.cs
//  Implementation of the Class TipoComprobante
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:23
///////////////////////////////////////////////////////////




public class TipoComprobante {

	private int codigoTipoComprobante;
	private string descripcionTipoComp;

	public TipoComprobante(){

	}

	~TipoComprobante(){

	}

	public virtual void Dispose(){

	}

}//end TipoComprobante