///////////////////////////////////////////////////////////
//  TipoMedicamento.cs
//  Implementation of the Class TipoMedicamento
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:23
///////////////////////////////////////////////////////////




public class TipoMedicamento {

	private int codigoTipoMedicamento;
	private string descripcionTipoMedic;
	private string presentacion;
	private string unidadMedida;
	//public StockMedicamento m_StockMedicamento;

	public TipoMedicamento(){

	}

	~TipoMedicamento(){

	}

	public virtual void Dispose(){

	}

}//end TipoMedicamento