///////////////////////////////////////////////////////////
//  TipoMovimiento.cs
//  Implementation of the Class TipoMovimiento
//  Generated by Enterprise Architect
//  Created on:      14-ene-2014 21:36:23
///////////////////////////////////////////////////////////




public class TipoMovimiento {

	private int codigoTipoMov;
	private string descripcionTipoMov;

	public TipoMovimiento(){

	}

	~TipoMovimiento(){

	}

	public virtual void Dispose(){

	}

}//end TipoMovimiento